# Generated by Django 4.1.6 on 2023-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('keywords', models.CharField(max_length=300)),
                ('descption', models.TextField()),
                ('image', models.ImageField(upload_to='area/image')),
            ],
        ),
    ]
