# Generated by Django 4.1.6 on 2023-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name_of_park',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
