# Generated by Django 4.1.6 on 2023-05-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_image_name_of_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
