# Generated by Django 4.1.6 on 2023-05-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_contact_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='request details', max_length=250),
        ),
    ]
